apiVersion: v1
kind: Service
metadata:
  name: mygraph-neo4j-nodeport
spec:
  type: NodePort
  ports:
  - name: mgmt
    port: 60001
    protocol: TCP
    targetPort: 7474
  - name: bolt
    port: 60002
    protocol: TCP
    targetPort: 7687
  selector:
    app.kubernetes.io/component: core
    app.kubernetes.io/instance: mygraph
    app.kubernetes.io/name: neo4j
