logging:
  level:
    root: INFO
    io.cstool.comply22: DEBUG
    spring.data: INFO
    org.springframework: INFO
    com.fasterxml.jackson.core: INFO
    com.fasterxml.jackson: INFO
    org.springframework.data.neo4j: INFO